### ISSUE TITLE
Proje raporunuz yüklenmemiş

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2019-2020-Skin-Cancer-Detection-appDermis-#1]
Proje raporunuz repoya yüklenmemiş. Acil yüklenmesi gerekli.

**Comment by mervetalakaci** [comment]
> Proje raporunuz repoya yüklenmemiş. Acil yüklenmesi gerekli.

Hocam wiki sayfamızın girişinde ekli, link vermiştik.

**Comment by fstasel** [comment]
Document branchine eklemişsiniz ok. Master branchinde görünmüyor. Oraya da eklerseniz iyi olur. /docs/ folder altına mesela. Gözden kaçmasın.
